global_frame: utm
robot_base_frame: odom
update_frequency: 3.0
publish_frequency: 1.0
static_map: false
rolling_window: true
resolution: 0.025
allow_unknown: false

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
 
